### ISSUE TITLE
How to visualize the part segmentation results?

### ISSUE THREAD

**Issue by Amazingren** [hithqd/PointRWKV#3]
Hi @hithqd 

Thanks for your impressive work, How to visualize the part segmentation results?

Bests,

**Comment by hithqd** [comment]
Thank you for your attention. The visualization codes come from [https://drive.google.com/file/d/1uHba4V3LawtWzTYuZ8FplpfosIWOZ3VP/view](url) and [https://github.com/Pang-Yatian/Point-MAE/blob/main/main_vis.py](url) with appropriate modifications.

**Comment by Amazingren** [comment]
> Thank you for your attention. The visualization codes come from [https://drive.google.com/file/d/1uHba4V3LawtWzTYuZ8FplpfosIWOZ3VP/view](url) and [https://github.com/Pang-Yatian/Point-MAE/blob/main/main_vis.py](url) with appropriate modifications.
> 
> Feel free to modify it according to your codebase.

Thanks for the kind feedback. :)

Best regards and many thanks,
